import os

files = os.listdir('.')
files.sort()

for svgFile in files:
    f = open(svgFile, "r")
    content = f.read()
    f.close()

    content = content.replace('''<?xml version="1.0" encoding="UTF-8"?>
<!-- Do not edit this file with editors other than draw.io -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<''', '<')
    content = content.replace('\'', '\\\'')
    svgFile = svgFile.replace('.svg', '')

    content = '\'' + svgFile + '\': \'' + content + '\',\n'

    output = open('output.txt', "a")
    output.write(content)
    output.close()
